goog.addDependency("base.js", ['goog'], []);
goog.addDependency("../cljs/core.js", ['cljs.core'], ['goog.string', 'goog.object', 'goog.math.Integer', 'goog.string.StringBuffer', 'goog.array', 'goog.math.Long']);
goog.addDependency("../leipzig/temperament.js", ['leipzig.temperament'], ['cljs.core']);
goog.addDependency("../cljs_bach/synthesis.js", ['cljs_bach.synthesis'], ['cljs.core']);
goog.addDependency("../leipzig/scale.js", ['leipzig.scale'], ['cljs.core']);
goog.addDependency("../leipzig/melody.js", ['leipzig.melody'], ['leipzig.scale', 'cljs.core']);
goog.addDependency("../rhapsody/lib/web_audio.js", ['rhapsody.lib.web_audio'], ['leipzig.temperament', 'cljs_bach.synthesis', 'cljs.core', 'leipzig.melody']);
goog.addDependency("../webmidi.min.js", ['webmidi.webmidi'], []);
goog.addDependency("../rhapsody/lib/midi.js", ['rhapsody.lib.midi'], ['cljs.core', 'webmidi.webmidi']);
goog.addDependency("../clojure/set.js", ['clojure.set'], ['cljs.core']);
goog.addDependency("../leipzig/chord.js", ['leipzig.chord'], ['leipzig.scale', 'cljs.core', 'clojure.set']);
goog.addDependency("../rhapsody/live.js", ['rhapsody.live'], ['leipzig.temperament', 'rhapsody.lib.web_audio', 'cljs_bach.synthesis', 'leipzig.scale', 'rhapsody.lib.midi', 'cljs.core', 'leipzig.melody', 'leipzig.chord']);
goog.addDependency("../demo/composition.js", ['demo.composition'], ['rhapsody.live', 'cljs.core']);
goog.addDependency("../boot/cljs/main691.js", ['boot.cljs.main691'], ['cljs.core', 'demo.composition']);
