#!/bin/sh

git_remote=$(git remote get-url origin)
target_dir="release-www"

# Ensure there is no existing $target_dir
rm -rf $target_dir

#
cd $target_dir
git init
git remote add origin $git_remote
git fetch --depth 1
git branch gh-pages origin/gh-pages

#
git symbolic-ref HEAD refs/heads/gh-pages
git reset

#
git add --all
git commit -m "Deployment at $(date)"

#
git push origin gh-pages

# Clean up $target_dir
rm -rf $target_dir
