#!/bin/sh

DOCKER_IMAGE="rhapsody"

# Build the docker image.
docker build -t $DOCKER_IMAGE --build-arg USER_ID=$(id -u) .

# Execute command specified by arguments, or bash.
command="bash"
if [ "$#" -ne "0" ]; then
    command=$@
fi

# Share host maven dependencies if a ~/.m2 directory exists.
maven_dir_vol=""
maven_dir="$HOME/.m2"
if [ ! -d "$maven_dir" ]; then
    # Otherwise, create a .m2 directory to save maven dependencies
    # across docker containers.
    maven_dir="./.m2"
    mkdir -p $maven_dir
fi
maven_dir_vol="-v $maven_dir:/home/code_executor/.m2"

# Share host ~/.boot if it exists.
boot_dir_vol=""
boot_dir="$HOME/.boot"
if [ -d "$boot_dir" ]; then
    boot_dir_vol="-v $boot_dir:/home/code_executor/.boot"
fi

# Run docker container.
docker run --rm -it\
       -p 1812:1812 \
       -p 1813:1813 \
       -p 1814:1814 \
       -p 1815:1815 \
       -v $(pwd):/app \
       $maven_dir_vol \
       $boot_dir_vol \
       $DOCKER_IMAGE $command
